### ISSUE TITLE
n_jobs argument with random forest

### ISSUE THREAD

**Issue by chrystalla92** [smazzanti/mrmr#16]
Version 0.2.4 introduces this bug: 
```TypeError: random_forest_classif() got an unexpected keyword argument 'n_jobs'```

Could you please have a look?

**Comment by smazzanti** [comment]
Hi @chrystalla92, thank you for pointing out! It should be fixed in version 0.2.5. Can you please check?

**Comment by chrystalla92** [comment]
Thank you, works in version 0.2.5.
